FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx tsc src/seeds/seed.ts --outDir dist --esModuleInterop --experimentalDecorators --emitDecoratorMetadata --skipLibCheck --resolveJsonModule --moduleResolution node

ENV NODE_ENV=development

CMD ["node", "dist/seeds/seed.js"]
